import "dotenv/config";
import { db } from "../db/index";
import { models } from "../db/schema";

const userId = process.argv[2];

if (!userId) {
  console.error("Please provide a userId: npx tsx src/utils/seed.ts <userId>");
  process.exit(1);
}

function generateSeedModels(userId: string): (typeof models.$inferInsert)[] {
  return [
    {
      name: "EKF Battery SOC Estimator",
      description: "Extended Kalman Filter model for accurate state-of-charge estimation in Li-ion cells under varying temperature conditions.",
      isPrivate: false,
      userId,
      modelType: "Extended Kalman Filter",
      alreadyEvaluated: true,
      weightedError: 2.34,
      allCells: 2.10,
      blindCells: 2.89,
      nonBlindedCells: 1.95,
      charging: 1.80,
      payload80kg: 2.10,
      payload448kgWithHvac: 2.65,
      payload448kgNoHvac: 2.40,
      payload1000kg: 3.10,
      standardCycles: 2.20,
      customCycles: 2.55,
      nMinus20C: 4.50,
      nMinus10C: 3.20,
      zeroC: 2.80,
      tenC: 2.30,
      twentyFiveC: 1.90,
      fortyC: 2.10,
      isocError: 1.50,
      currentSensorError: 0.80,
      allDriveCyclesAvgRmse: 2.15,
      allDriveCyclesAvgMae: 1.75,
      allDriveCyclesAvgMaxe: 5.40,
    },
    {
      name: "EKF-UKF Dual Estimator",
      description: "Extended Kalman Filter with unscented transform augmentation for improved nonlinear SOC estimation.",
      isPrivate: false,
      userId,
      modelType: "Extended Kalman Filter",
      alreadyEvaluated: true,
      weightedError: 2.88,
      allCells: 2.70,
      blindCells: 3.15,
      nonBlindedCells: 2.50,
      charging: 2.20,
      payload80kg: 2.75,
      payload448kgWithHvac: 3.10,
      payload448kgNoHvac: 2.90,
      payload1000kg: 3.55,
      standardCycles: 2.80,
      customCycles: 3.00,
      nMinus20C: 5.20,
      nMinus10C: 3.90,
      zeroC: 3.30,
      tenC: 2.85,
      twentyFiveC: 2.40,
      fortyC: 2.65,
      isocError: 1.95,
      currentSensorError: 1.05,
      allDriveCyclesAvgRmse: 2.70,
      allDriveCyclesAvgMae: 2.20,
      allDriveCyclesAvgMaxe: 6.50,
    },
    {
      name: "Adaptive EKF v3",
      description: "Adaptive noise covariance Extended Kalman Filter with online parameter tuning for battery SOC.",
      isPrivate: false,
      userId,
      modelType: "Extended Kalman Filter",
      alreadyEvaluated: true,
      weightedError: 1.95,
      allCells: 1.80,
      blindCells: 2.20,
      nonBlindedCells: 1.68,
      charging: 1.55,
      payload80kg: 1.85,
      payload448kgWithHvac: 2.30,
      payload448kgNoHvac: 2.05,
      payload1000kg: 2.60,
      standardCycles: 1.90,
      customCycles: 2.05,
      nMinus20C: 4.00,
      nMinus10C: 2.85,
      zeroC: 2.40,
      tenC: 1.98,
      twentyFiveC: 1.62,
      fortyC: 1.80,
      isocError: 1.28,
      currentSensorError: 0.70,
      allDriveCyclesAvgRmse: 1.88,
      allDriveCyclesAvgMae: 1.52,
      allDriveCyclesAvgMaxe: 4.65,
    },
    {
      name: "LSTM SOC Predictor v2",
      description: "Long Short-Term Memory neural network trained on multi-cycle drive data for robust SOC prediction.",
      isPrivate: false,
      userId,
      modelType: "LSTM",
      alreadyEvaluated: true,
      weightedError: 1.87,
      allCells: 1.70,
      blindCells: 2.10,
      nonBlindedCells: 1.60,
      charging: 1.40,
      payload80kg: 1.75,
      payload448kgWithHvac: 2.20,
      payload448kgNoHvac: 2.00,
      payload1000kg: 2.50,
      standardCycles: 1.80,
      customCycles: 1.95,
      nMinus20C: 3.80,
      nMinus10C: 2.70,
      zeroC: 2.20,
      tenC: 1.85,
      twentyFiveC: 1.50,
      fortyC: 1.70,
      isocError: 1.20,
      currentSensorError: 0.65,
      allDriveCyclesAvgRmse: 1.72,
      allDriveCyclesAvgMae: 1.40,
      allDriveCyclesAvgMaxe: 4.20,
    },
    {
      name: "Bidirectional LSTM SOC",
      description: "Bidirectional LSTM architecture for SOC estimation leveraging both past and future sequence context.",
      isPrivate: false,
      userId,
      modelType: "LSTM",
      alreadyEvaluated: true,
      weightedError: 1.72,
      allCells: 1.58,
      blindCells: 1.92,
      nonBlindedCells: 1.48,
      charging: 1.30,
      payload80kg: 1.65,
      payload448kgWithHvac: 2.05,
      payload448kgNoHvac: 1.85,
      payload1000kg: 2.30,
      standardCycles: 1.68,
      customCycles: 1.80,
      nMinus20C: 3.60,
      nMinus10C: 2.58,
      zeroC: 2.12,
      tenC: 1.74,
      twentyFiveC: 1.40,
      fortyC: 1.60,
      isocError: 1.12,
      currentSensorError: 0.60,
      allDriveCyclesAvgRmse: 1.65,
      allDriveCyclesAvgMae: 1.35,
      allDriveCyclesAvgMaxe: 4.00,
    },
    {
      name: "Stacked LSTM Deep Estimator",
      description: "Three-layer stacked LSTM network for deep temporal feature extraction in battery SOC estimation.",
      isPrivate: false,
      userId,
      modelType: "LSTM",
      alreadyEvaluated: true,
      weightedError: 2.10,
      allCells: 1.95,
      blindCells: 2.38,
      nonBlindedCells: 1.80,
      charging: 1.62,
      payload80kg: 2.00,
      payload448kgWithHvac: 2.50,
      payload448kgNoHvac: 2.25,
      payload1000kg: 2.85,
      standardCycles: 2.05,
      customCycles: 2.18,
      nMinus20C: 4.20,
      nMinus10C: 3.05,
      zeroC: 2.55,
      tenC: 2.12,
      twentyFiveC: 1.75,
      fortyC: 1.95,
      isocError: 1.40,
      currentSensorError: 0.75,
      allDriveCyclesAvgRmse: 2.00,
      allDriveCyclesAvgMae: 1.65,
      allDriveCyclesAvgMaxe: 5.00,
    },
    {
      name: "GRU Hybrid SOC Model",
      description: "Gated Recurrent Unit combined with physics-based Coulomb counting for hybrid SOC estimation.",
      isPrivate: false,
      userId,
      modelType: "GRU",
      alreadyEvaluated: true,
      weightedError: 2.05,
      allCells: 1.90,
      blindCells: 2.30,
      nonBlindedCells: 1.78,
      charging: 1.60,
      payload80kg: 1.95,
      payload448kgWithHvac: 2.40,
      payload448kgNoHvac: 2.15,
      payload1000kg: 2.75,
      standardCycles: 2.00,
      customCycles: 2.12,
      nMinus20C: 4.10,
      nMinus10C: 2.95,
      zeroC: 2.45,
      tenC: 2.05,
      twentyFiveC: 1.70,
      fortyC: 1.88,
      isocError: 1.35,
      currentSensorError: 0.72,
      allDriveCyclesAvgRmse: 1.95,
      allDriveCyclesAvgMae: 1.58,
      allDriveCyclesAvgMaxe: 4.80,
    },
    {
      name: "Lightweight GRU Edge Model",
      description: "Compact GRU architecture optimized for embedded BMS deployment with minimal memory footprint.",
      isPrivate: false,
      userId,
      modelType: "GRU",
      alreadyEvaluated: true,
      weightedError: 2.55,
      allCells: 2.38,
      blindCells: 2.85,
      nonBlindedCells: 2.18,
      charging: 2.00,
      payload80kg: 2.45,
      payload448kgWithHvac: 2.95,
      payload448kgNoHvac: 2.68,
      payload1000kg: 3.20,
      standardCycles: 2.50,
      customCycles: 2.62,
      nMinus20C: 4.80,
      nMinus10C: 3.50,
      zeroC: 2.95,
      tenC: 2.55,
      twentyFiveC: 2.10,
      fortyC: 2.35,
      isocError: 1.72,
      currentSensorError: 0.92,
      allDriveCyclesAvgRmse: 2.42,
      allDriveCyclesAvgMae: 1.98,
      allDriveCyclesAvgMaxe: 5.85,
    },
    {
      name: "Deep GRU Attention Model",
      description: "GRU network augmented with self-attention mechanism for improved long-range dependency modeling.",
      isPrivate: false,
      userId,
      modelType: "GRU",
      alreadyEvaluated: true,
      weightedError: 1.80,
      allCells: 1.65,
      blindCells: 2.02,
      nonBlindedCells: 1.55,
      charging: 1.38,
      payload80kg: 1.72,
      payload448kgWithHvac: 2.15,
      payload448kgNoHvac: 1.92,
      payload1000kg: 2.42,
      standardCycles: 1.76,
      customCycles: 1.88,
      nMinus20C: 3.72,
      nMinus10C: 2.68,
      zeroC: 2.22,
      tenC: 1.82,
      twentyFiveC: 1.48,
      fortyC: 1.68,
      isocError: 1.18,
      currentSensorError: 0.63,
      allDriveCyclesAvgRmse: 1.72,
      allDriveCyclesAvgMae: 1.40,
      allDriveCyclesAvgMaxe: 4.25,
    },
    {
      name: "Transformer SOC Network",
      description: "Attention-based Transformer model for sequence-to-sequence SOC estimation across diverse drive cycles.",
      isPrivate: false,
      userId,
      modelType: "Transformer",
      alreadyEvaluated: true,
      weightedError: 1.65,
      allCells: 1.50,
      blindCells: 1.88,
      nonBlindedCells: 1.40,
      charging: 1.20,
      payload80kg: 1.55,
      payload448kgWithHvac: 1.95,
      payload448kgNoHvac: 1.75,
      payload1000kg: 2.20,
      standardCycles: 1.60,
      customCycles: 1.72,
      nMinus20C: 3.40,
      nMinus10C: 2.45,
      zeroC: 2.00,
      tenC: 1.65,
      twentyFiveC: 1.30,
      fortyC: 1.50,
      isocError: 1.05,
      currentSensorError: 0.55,
      allDriveCyclesAvgRmse: 1.55,
      allDriveCyclesAvgMae: 1.25,
      allDriveCyclesAvgMaxe: 3.80,
    },
    {
      name: "Temporal Fusion Transformer",
      description: "Multi-horizon Temporal Fusion Transformer adapted for battery SOC estimation with interpretable attention.",
      isPrivate: false,
      userId,
      modelType: "Transformer",
      alreadyEvaluated: true,
      weightedError: 1.52,
      allCells: 1.38,
      blindCells: 1.72,
      nonBlindedCells: 1.28,
      charging: 1.10,
      payload80kg: 1.42,
      payload448kgWithHvac: 1.80,
      payload448kgNoHvac: 1.60,
      payload1000kg: 2.05,
      standardCycles: 1.48,
      customCycles: 1.58,
      nMinus20C: 3.15,
      nMinus10C: 2.28,
      zeroC: 1.85,
      tenC: 1.52,
      twentyFiveC: 1.18,
      fortyC: 1.38,
      isocError: 0.95,
      currentSensorError: 0.50,
      allDriveCyclesAvgRmse: 1.42,
      allDriveCyclesAvgMae: 1.15,
      allDriveCyclesAvgMaxe: 3.50,
    },
    {
      name: "Lightweight Transformer SOC",
      description: "Distilled Transformer model with reduced parameter count for real-time SOC estimation on BMS hardware.",
      isPrivate: false,
      userId,
      modelType: "Transformer",
      alreadyEvaluated: true,
      weightedError: 1.90,
      allCells: 1.75,
      blindCells: 2.15,
      nonBlindedCells: 1.62,
      charging: 1.42,
      payload80kg: 1.80,
      payload448kgWithHvac: 2.25,
      payload448kgNoHvac: 2.02,
      payload1000kg: 2.52,
      standardCycles: 1.85,
      customCycles: 1.98,
      nMinus20C: 3.88,
      nMinus10C: 2.78,
      zeroC: 2.28,
      tenC: 1.90,
      twentyFiveC: 1.55,
      fortyC: 1.75,
      isocError: 1.22,
      currentSensorError: 0.65,
      allDriveCyclesAvgRmse: 1.80,
      allDriveCyclesAvgMae: 1.45,
      allDriveCyclesAvgMaxe: 4.40,
    },
    {
      name: "Coulomb Counter Baseline",
      description: "Simple Coulomb counting baseline model with drift correction. Used as benchmark for learned models.",
      isPrivate: false,
      userId,
      modelType: "Coulomb Counter",
      alreadyEvaluated: true,
      weightedError: 4.80,
      allCells: 4.50,
      blindCells: 5.30,
      nonBlindedCells: 4.20,
      charging: 3.80,
      payload80kg: 4.60,
      payload448kgWithHvac: 5.50,
      payload448kgNoHvac: 5.10,
      payload1000kg: 6.20,
      standardCycles: 4.70,
      customCycles: 4.95,
      nMinus20C: 8.50,
      nMinus10C: 6.40,
      zeroC: 5.50,
      tenC: 4.80,
      twentyFiveC: 3.90,
      fortyC: 4.30,
      isocError: 3.20,
      currentSensorError: 1.80,
      allDriveCyclesAvgRmse: 4.55,
      allDriveCyclesAvgMae: 3.90,
      allDriveCyclesAvgMaxe: 10.20,
    },
    {
      name: "Coulomb Counter with OCV Correction",
      description: "Enhanced Coulomb counter using open-circuit voltage lookup tables for periodic drift correction.",
      isPrivate: false,
      userId,
      modelType: "Coulomb Counter",
      alreadyEvaluated: true,
      weightedError: 3.95,
      allCells: 3.70,
      blindCells: 4.40,
      nonBlindedCells: 3.45,
      charging: 3.10,
      payload80kg: 3.80,
      payload448kgWithHvac: 4.55,
      payload448kgNoHvac: 4.20,
      payload1000kg: 5.10,
      standardCycles: 3.88,
      customCycles: 4.05,
      nMinus20C: 7.20,
      nMinus10C: 5.40,
      zeroC: 4.60,
      tenC: 3.95,
      twentyFiveC: 3.20,
      fortyC: 3.55,
      isocError: 2.65,
      currentSensorError: 1.50,
      allDriveCyclesAvgRmse: 3.78,
      allDriveCyclesAvgMae: 3.20,
      allDriveCyclesAvgMaxe: 8.80,
    },
    {
      name: "NARX Recurrent Estimator",
      description: "Nonlinear AutoRegressive with eXogenous inputs model for SOC estimation using voltage and current history.",
      isPrivate: true,
      userId,
      modelType: "NARX",
      alreadyEvaluated: false,
    },
    {
      name: "NARX Temperature-Aware Model",
      description: "NARX model with explicit temperature exogenous inputs for improved cold and hot weather SOC estimation.",
      isPrivate: false,
      userId,
      modelType: "NARX",
      alreadyEvaluated: true,
      weightedError: 2.42,
      allCells: 2.25,
      blindCells: 2.72,
      nonBlindedCells: 2.08,
      charging: 1.88,
      payload80kg: 2.32,
      payload448kgWithHvac: 2.82,
      payload448kgNoHvac: 2.55,
      payload1000kg: 3.18,
      standardCycles: 2.38,
      customCycles: 2.50,
      nMinus20C: 4.65,
      nMinus10C: 3.38,
      zeroC: 2.85,
      tenC: 2.42,
      twentyFiveC: 1.98,
      fortyC: 2.20,
      isocError: 1.62,
      currentSensorError: 0.88,
      allDriveCyclesAvgRmse: 2.30,
      allDriveCyclesAvgMae: 1.88,
      allDriveCyclesAvgMaxe: 5.55,
    },
    {
      name: "Deep NARX with Regularization",
      description: "Deep NARX network with L2 regularization and dropout for robust generalization across battery chemistries.",
      isPrivate: false,
      userId,
      modelType: "NARX",
      alreadyEvaluated: true,
      weightedError: 2.18,
      allCells: 2.02,
      blindCells: 2.45,
      nonBlindedCells: 1.88,
      charging: 1.68,
      payload80kg: 2.08,
      payload448kgWithHvac: 2.58,
      payload448kgNoHvac: 2.32,
      payload1000kg: 2.92,
      standardCycles: 2.12,
      customCycles: 2.25,
      nMinus20C: 4.35,
      nMinus10C: 3.12,
      zeroC: 2.62,
      tenC: 2.18,
      twentyFiveC: 1.80,
      fortyC: 2.00,
      isocError: 1.45,
      currentSensorError: 0.78,
      allDriveCyclesAvgRmse: 2.08,
      allDriveCyclesAvgMae: 1.70,
      allDriveCyclesAvgMaxe: 5.05,
    },
    {
      name: "FNN Quick Estimator",
      description: "Feedforward Neural Network for fast, low-latency SOC estimation suitable for embedded BMS deployment.",
      isPrivate: false,
      userId,
      modelType: "FNN",
      alreadyEvaluated: true,
      weightedError: 3.10,
      allCells: 2.90,
      blindCells: 3.45,
      nonBlindedCells: 2.70,
      charging: 2.50,
      payload80kg: 3.00,
      payload448kgWithHvac: 3.60,
      payload448kgNoHvac: 3.30,
      payload1000kg: 4.00,
      standardCycles: 3.05,
      customCycles: 3.20,
      nMinus20C: 5.80,
      nMinus10C: 4.30,
      zeroC: 3.70,
      tenC: 3.10,
      twentyFiveC: 2.60,
      fortyC: 2.90,
      isocError: 2.10,
      currentSensorError: 1.10,
      allDriveCyclesAvgRmse: 2.95,
      allDriveCyclesAvgMae: 2.45,
      allDriveCyclesAvgMaxe: 6.80,
    },
    {
      name: "Deep FNN SOC Estimator",
      description: "Six-layer feedforward network with batch normalization for stable and accurate SOC prediction.",
      isPrivate: false,
      userId,
      modelType: "FNN",
      alreadyEvaluated: true,
      weightedError: 2.72,
      allCells: 2.55,
      blindCells: 3.05,
      nonBlindedCells: 2.35,
      charging: 2.15,
      payload80kg: 2.62,
      payload448kgWithHvac: 3.18,
      payload448kgNoHvac: 2.88,
      payload1000kg: 3.55,
      standardCycles: 2.68,
      customCycles: 2.80,
      nMinus20C: 5.15,
      nMinus10C: 3.78,
      zeroC: 3.22,
      tenC: 2.72,
      twentyFiveC: 2.28,
      fortyC: 2.52,
      isocError: 1.85,
      currentSensorError: 0.98,
      allDriveCyclesAvgRmse: 2.58,
      allDriveCyclesAvgMae: 2.12,
      allDriveCyclesAvgMaxe: 6.10,
    },
    {
      name: "FNN Ensemble SOC Model",
      description: "Ensemble of five FNN models with majority voting for robust and uncertainty-aware SOC estimation.",
      isPrivate: false,
      userId,
      modelType: "FNN",
      alreadyEvaluated: true,
      weightedError: 2.45,
      allCells: 2.28,
      blindCells: 2.75,
      nonBlindedCells: 2.10,
      charging: 1.90,
      payload80kg: 2.35,
      payload448kgWithHvac: 2.88,
      payload448kgNoHvac: 2.60,
      payload1000kg: 3.22,
      standardCycles: 2.40,
      customCycles: 2.52,
      nMinus20C: 4.70,
      nMinus10C: 3.42,
      zeroC: 2.88,
      tenC: 2.45,
      twentyFiveC: 2.02,
      fortyC: 2.22,
      isocError: 1.65,
      currentSensorError: 0.88,
      allDriveCyclesAvgRmse: 2.32,
      allDriveCyclesAvgMae: 1.90,
      allDriveCyclesAvgMaxe: 5.60,
    },
    {
      name: "Hybrid EKF-LSTM",
      description: "Hybrid model combining Extended Kalman Filter state estimation with LSTM-based error correction.",
      isPrivate: false,
      userId,
      modelType: "Hybrid Model",
      alreadyEvaluated: true,
      weightedError: 1.72,
      allCells: 1.58,
      blindCells: 1.95,
      nonBlindedCells: 1.48,
      charging: 1.28,
      payload80kg: 1.62,
      payload448kgWithHvac: 2.05,
      payload448kgNoHvac: 1.82,
      payload1000kg: 2.28,
      standardCycles: 1.68,
      customCycles: 1.80,
      nMinus20C: 3.55,
      nMinus10C: 2.55,
      zeroC: 2.10,
      tenC: 1.72,
      twentyFiveC: 1.38,
      fortyC: 1.58,
      isocError: 1.10,
      currentSensorError: 0.58,
      allDriveCyclesAvgRmse: 1.62,
      allDriveCyclesAvgMae: 1.32,
      allDriveCyclesAvgMaxe: 3.95,
    },
    {
      name: "Physics-Informed Neural Hybrid",
      description: "Hybrid model combining electrochemical single-particle model constraints with deep learning corrections.",
      isPrivate: false,
      userId,
      modelType: "Hybrid Model",
      alreadyEvaluated: true,
      weightedError: 1.48,
      allCells: 1.35,
      blindCells: 1.68,
      nonBlindedCells: 1.25,
      charging: 1.08,
      payload80kg: 1.40,
      payload448kgWithHvac: 1.75,
      payload448kgNoHvac: 1.55,
      payload1000kg: 1.98,
      standardCycles: 1.44,
      customCycles: 1.55,
      nMinus20C: 3.05,
      nMinus10C: 2.20,
      zeroC: 1.78,
      tenC: 1.48,
      twentyFiveC: 1.15,
      fortyC: 1.32,
      isocError: 0.92,
      currentSensorError: 0.48,
      allDriveCyclesAvgRmse: 1.38,
      allDriveCyclesAvgMae: 1.10,
      allDriveCyclesAvgMaxe: 3.35,
    },
    {
      name: "KF-GRU Cascaded Hybrid",
      description: "Cascaded architecture where Kalman Filter pre-filters noisy measurements before GRU refinement.",
      isPrivate: false,
      userId,
      modelType: "Hybrid Model",
      alreadyEvaluated: true,
      weightedError: 1.98,
      allCells: 1.82,
      blindCells: 2.22,
      nonBlindedCells: 1.70,
      charging: 1.50,
      payload80kg: 1.90,
      payload448kgWithHvac: 2.35,
      payload448kgNoHvac: 2.10,
      payload1000kg: 2.65,
      standardCycles: 1.92,
      customCycles: 2.05,
      nMinus20C: 4.05,
      nMinus10C: 2.90,
      zeroC: 2.42,
      tenC: 1.98,
      twentyFiveC: 1.62,
      fortyC: 1.82,
      isocError: 1.30,
      currentSensorError: 0.70,
      allDriveCyclesAvgRmse: 1.88,
      allDriveCyclesAvgMae: 1.52,
      allDriveCyclesAvgMaxe: 4.58,
    },
    {
      name: "Standard Kalman SOC Filter",
      description: "Classic linear Kalman Filter for SOC estimation with simplified battery equivalent circuit model.",
      isPrivate: false,
      userId,
      modelType: "Kalman Filter",
      alreadyEvaluated: true,
      weightedError: 3.55,
      allCells: 3.30,
      blindCells: 3.95,
      nonBlindedCells: 3.08,
      charging: 2.80,
      payload80kg: 3.42,
      payload448kgWithHvac: 4.05,
      payload448kgNoHvac: 3.75,
      payload1000kg: 4.55,
      standardCycles: 3.48,
      customCycles: 3.65,
      nMinus20C: 6.50,
      nMinus10C: 4.90,
      zeroC: 4.15,
      tenC: 3.55,
      twentyFiveC: 2.90,
      fortyC: 3.22,
      isocError: 2.42,
      currentSensorError: 1.30,
      allDriveCyclesAvgRmse: 3.38,
      allDriveCyclesAvgMae: 2.80,
      allDriveCyclesAvgMaxe: 7.80,
    },
    {
      name: "Dual Kalman Filter Estimator",
      description: "Dual Kalman Filter simultaneously estimating SOC and battery model parameters for adaptive performance.",
      isPrivate: false,
      userId,
      modelType: "Kalman Filter",
      alreadyEvaluated: true,
      weightedError: 3.12,
      allCells: 2.92,
      blindCells: 3.48,
      nonBlindedCells: 2.70,
      charging: 2.45,
      payload80kg: 3.00,
      payload448kgWithHvac: 3.58,
      payload448kgNoHvac: 3.28,
      payload1000kg: 4.02,
      standardCycles: 3.05,
      customCycles: 3.22,
      nMinus20C: 5.78,
      nMinus10C: 4.32,
      zeroC: 3.68,
      tenC: 3.12,
      twentyFiveC: 2.55,
      fortyC: 2.85,
      isocError: 2.12,
      currentSensorError: 1.15,
      allDriveCyclesAvgRmse: 2.98,
      allDriveCyclesAvgMae: 2.45,
      allDriveCyclesAvgMaxe: 6.92,
    },
  ];
}

async function seed() {
  console.log("Starting seed...");
  console.log(`Using userId: ${userId}`);

  const seedModels = generateSeedModels(userId);

  console.log(`Inserting ${seedModels.length} models...`);
  const inserted = await db
    .insert(models)
    .values(seedModels)
    .returning({ id: models.id, name: models.name });

  console.log("Seeded models:");
  inserted.forEach((m) => console.log(`  - [${m.id}] ${m.name}`));

  console.log("Seed complete.");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});