import { relations } from "drizzle-orm";
import { pgEnum, pgTable, text, timestamp, boolean, index, serial, integer, doublePrecision } from "drizzle-orm/pg-core";

export const modelTypeEnum = pgEnum('model_type', ['Machine Learning', 'Kalman Filter', 'Extended Kalman Filter', 'Other Kalman Filter', 'FNN', 'LSTM', 'GRU', 'NARX', 'Transformer', 'Other Neural Network', 'Coulomb Counter', 'Hybrid Model', 'Not Specified']);
/*
    AUTH TABLES -- GENERATED BY better-auth
*/
export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  role: text("role"),
  banned: boolean("banned").default(false),
  banReason: text("ban_reason"),
  banExpires: timestamp("ban_expires"),
  username: text("username").unique(),
  displayUsername: text("display_username"),
  first_name: text("first_name").notNull(),
  last_name: text("last_name").notNull(),
  academic_affiliation: text("academic_affiliation").notNull(),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    impersonatedBy: text("impersonated_by"),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
  models: many(models)
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));
/* 
    MODELS TABLE
*/
export const models = pgTable(
  "models",
  {
    id: serial("id").primaryKey(),
    name: text("name").notNull(),
    description: text("description").notNull(),
    isPrivate: boolean("isPrivate").notNull().default(true),
    userId: text("owner_user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    modelType: modelTypeEnum('model_type').notNull().default('Not Specified'),

    // DATA 
    alreadyEvaluated: boolean('already_evaluated').default(false), // Has the model been evaluated?
    // Error metrics
    weightedError: doublePrecision('weighted_error'),
    allCells: doublePrecision('all_cells'),
    blindCells: doublePrecision('blind_cells'),
    nonBlindedCells: doublePrecision('non_blinded_cells'),

    // Drive cycle conditions
    charging: doublePrecision('charging'),
    payload80kg: doublePrecision('payload_80kg'),
    payload448kgWithHvac: doublePrecision('payload_448kg_with_hvac'),
    payload448kgNoHvac: doublePrecision('payload_448kg_no_hvac'),
    payload1000kg: doublePrecision('payload_1000kg'),

    // Cycle types
    standardCycles: doublePrecision('standard_cycles'),
    customCycles: doublePrecision('custom_cycles'),

    // Temperature conditions
    nMinus20C: doublePrecision('n20c'),
    nMinus10C: doublePrecision('n10c'),
    zeroC: doublePrecision('0c'),
    tenC: doublePrecision('10c'),
    twentyFiveC: doublePrecision('25c'),
    fortyC: doublePrecision('40c'),

    // Sensor errors
    isocError: doublePrecision('isoc_error'),
    currentSensorError: doublePrecision('current_sensor_error'),

    // Drive cycle aggregates
    allDriveCyclesAvgRmse: doublePrecision('all_drive_cycles_avg_rmse'),
    allDriveCyclesAvgMae: doublePrecision('all_drive_cycles_avg_mae'),
    allDriveCyclesAvgMaxe: doublePrecision('all_drive_cycles_avg_maxe'),

  }
);

export const modelRelations = relations(models, ({ one }) => ({
  owner: one(user, {
    fields: [models.userId],   // foreign key column in models
    references: [user.id],     // referenced column in users
  }),
}));
