# Generated by Django 5.1.2 on 2025-04-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_alter_submission_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='model_type',
            field=models.TextField(choices=[('ML', 'Machine Learning'), ('KF', 'Kalman Filter'), ('NA', 'Not Specified'), ('EKF', 'Extended Kalman Filter'), ('OKF', 'Other Kalman Filter'), ('FNN', 'FNN'), ('LSTM', 'LSTM'), ('GRU', 'GRU'), ('NARX', 'NARX'), ('T', 'Transformer'), ('ONN', 'Other Neural Network'), ('HM', 'Hybrid Model'), ('CC', 'Coulomb Counter')], default='NA', max_length=4),
        ),
    ]
